# =============================================================
# VirtualHost: api.empresa.local
# Parte 2 — Servidor Apache — Servicios Telemáticos
# IP: 192.168.50.10  (mismo servidor, distinto ServerName)
# =============================================================

<VirtualHost *:80>
    ServerName api.empresa.local

    DocumentRoot /var/www/api.empresa.local/html

    # ---- Directorio raíz ----
    <Directory /var/www/api.empresa.local/html>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    # ---- Módulo Rewrite ----
    RewriteEngine On

    # ---- Cabeceras REST/API ----
    Header always set X-Content-Type-Options  "nosniff"
    Header always set Access-Control-Allow-Origin  "*"
    Header always set Access-Control-Allow-Methods "GET, POST, OPTIONS"
    Header always set Access-Control-Allow-Headers "Content-Type, Authorization"

    # ---- Logs ----
    ErrorLog  ${APACHE_LOG_DIR}/api.empresa.local-error.log
    CustomLog ${APACHE_LOG_DIR}/api.empresa.local-access.log combined

</VirtualHost>
