# Sitio de medicion de compresion - Parte 2.
<VirtualHost *:80>
    ServerName parcial.empresa.local
    DocumentRoot /var/www/parcial.empresa.local/html
    <Directory /var/www/parcial.empresa.local/html>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>
    Header always set X-Content-Type-Options "nosniff"
    ErrorLog  ${APACHE_LOG_DIR}/parcial.empresa.local-error.log
    CustomLog ${APACHE_LOG_DIR}/parcial.empresa.local-access.log combined
</VirtualHost>
